version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: AhBaegopa
    volumes:
      - ./postgres:/var/lib/postgresql/data
